services:
  mysql:
    image: mysql:8.0
    container_name: uni-mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env.dev
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}   # dev 편의상 동일
      TZ: Asia/Seoul
    ports:
      - "13306:3306"                    # DB툴: localhost:13306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: uni-backend:dev
    container_name: uni-backend
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.dev
    environment:
      # 컨테이너 내부에서 DB는 서비스명 mysql 로 접속
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SERVER_ADDRESS: 0.0.0.0     # 외부 바인딩 보장
    ports:
      - "8080:8080"               # 호스트 8080 → 컨테이너 8080
    restart: unless-stopped

volumes:
  mysql_data:
